# config.yaml
model:
  name: "RandomForestClassifier"
  params:
    n_estimators: 100
    max_depth: 5

data:
  path: "data/dataset.csv"
  split_ratio: 0.8
import yaml

with open("config.yaml", "r") as file:
    config = yaml.safe_load(file)

print(config['model']['name'])  # Output: RandomForestClassifier
